{
 "title": "Ganet Cluster Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Ganeti Cluster Name",
    "query": {
     "query": "label_values(ganeti_cluster_node_count,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ganeti Cluster",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (ganeti_cluster_node_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ganeti Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ganeti_cluster_node_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ganeti_node_mtotal)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ganeti_node_ctotal)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ganeti_node_dtotal)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocatable Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_hspace_allocatable_instances)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_cluster_instance_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated Instance Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ganeti_instance_oper_ram)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Allocated vCPU Cores",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_instance_oper_vcpus)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Belegung",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(ganeti_cluster_instance_count / (ganeti_hspace_allocatable_instances + ganeti_cluster_instance_count)) * 100",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Cluster Balancing",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_hbal_initial_score - ganeti_hbal_target_score",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}