{
 "title": "Ganeti",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "Cluster Name", "query": { "query": "label_values(cluster)" } },
   {
    "name": "node_groups",
    "label": "Node Groups",
    "query": {
     "query": "label_values(ganeti_hbal_initial_score{cluster=\"$cluster\"},node_group)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_cluster_node_count{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_cluster_offline_nodes{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_cluster_instance_count{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_node_ctotal{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_node_mtotal{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Disk Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_node_dtotal{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Instance CPU Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ganeti_instance_oper_vcpus{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AVG Instance Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ganeti_instance_oper_ram{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocatable Instances",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_hspace_allocatable_instances{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster CPU Ratio",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_instance_oper_vcpus{cluster=\"$cluster\"}) / sum(ganeti_node_ctotal{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Memory allocated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_instance_oper_ram{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance vCPUs allocated",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ganeti_instance_oper_vcpus{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs in Error State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_cluster_jobs{cluster=\"$cluster\", job_status=\"error\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Job Queue Wait Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ganeti_job_wait_time{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Startup Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_job_run_time{cluster=\"$cluster\", job_operation=\"OP_INSTANCE_START\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instance Creation Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_job_run_time{cluster=\"$cluster\", job_operation=\"OP_INSTANCE_CREATE\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Verify Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(ganeti_job_run_time{cluster=\"$cluster\", job_operation=~\"OP_CLUSTER_VERIFY_GROUP\"}) + avg(ganeti_job_run_time{cluster=\"$cluster\", job_operation=~\"OP_CLUSTER_VERIFY\"}) + avg(ganeti_job_run_time{cluster=\"$cluster\", job_operation=~\"OP_CLUSTER_VERIFY_CONFIG\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Balancing Scores", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Current Cluster Score (Node Group $node_groups)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "repeat": "node_groups",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_hbal_initial_score{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Achievable Score (Node Group $node_groups)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 27 },
   "repeat": "node_groups",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ganeti_hbal_target_score{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Cluster Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(ganeti_node_mtotal{cluster=\"$cluster\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum(ganeti_node_mfree{cluster=\"$cluster\"})",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Cluster Storage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(ganeti_node_dtotal{cluster=\"$cluster\"})",
     "legendFormat": "Total Disk Storage"
    },
    {
     "expr": "sum(ganeti_node_dfree{cluster=\"$cluster\"})",
     "legendFormat": "Free Disk Storage"
    }
   ]
  },
  {
   "title": "Cluster Instances",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "ganeti_cluster_instance_count{cluster=\"$cluster\"}",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Cluster Allocatable Instances",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "ganeti_hspace_allocatable_instances{cluster=\"$cluster\"}",
     "legendFormat": "Instances"
    }
   ]
  },
  {
   "title": "Cluster Balancing Scores",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "ganeti_hbal_initial_score{cluster=\"$cluster\", node_group=\"$node_groups\"}",
     "legendFormat": "Current Score (Node Group {{node_group}})"
    },
    {
     "expr": "ganeti_hbal_target_score{cluster=\"$cluster\", node_group=\"$node_groups\"}",
     "legendFormat": "Achievable Score (Node Group {{node_group}})"
    }
   ]
  },
  { "title": "Node Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Primary Instances per Node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "ganeti_node_pinst_cnt{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Secondary Instances per Node",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "ganeti_node_sinst_cnt{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "ganeti_node_mfree{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node Available Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "ganeti_node_dfree{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node vCPU vs CPU Ratio",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "ganeti_node_p_oper_vcpus{cluster=\"$cluster\"} / ganeti_node_ctotal{cluster=\"$cluster\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Job Queue", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Job Queue States",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "ganeti_cluster_jobs{cluster=\"$cluster\"}",
     "legendFormat": "{{job_status}}"
    }
   ]
  },
  {
   "title": "Average Job Execution Time per Operation ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(job_operation) (ganeti_job_run_time{cluster=\"$cluster\"})",
     "legendFormat": "{{job_operation}}"
    }
   ]
  }
 ]
}